<?php

/**
 * Class Info
 */

class Info
{

    /**
     * @var array
     */
    public static $slogan = array(
        1 => 'In here, you\'ll always find what you need.',
        2 => 'Shop for the best deals on everything you love and need.',
        3 => 'Shop your way through our amazing products.',
        4 => 'This is a one stop shop for your everyday needs.',
        5 => 'Shop with confidence in our all in one store.',
        6 => 'Get ready to discover amazing items in our amazing store.',
        7 => 'Your shopping for a better life begins here.',
        8 => 'Shop the best products from all over the world.',
        9 => 'Find the best deals and shop the best products here with us.',
        10 => 'Shop smart and save big with us.',
        11 => 'Shop what you desire',
        12 => 'Your shopping experience redefined.',
        13 => 'We are the gateway for your unique shopping experience.',
        14 => 'Keep calm and keep shopping',
        15 => 'A place where you can buy anything',
        16 => 'One click away from getting what you want',
        17 => 'We provide hustle free and premium products.',
        18 => 'Amazing place for online shopping',
        19 => 'Your one stop destination for everything.',
        20 => 'Buy more, Pay less',
        21 => 'Enjoy the never ending shopping experience',
        22 => 'Stop thinking, start shopping',
        23 => 'We Make Shopping Easy.',
        24 => 'The Best Deals Ever!',
        25 => 'Buy What You Love, Love What You Buy.',
        26 => 'The Quality You Expect, The Price You Deserve',
        27 => 'The More You Buy, The More You Save!',
        28 => 'The Most Popular Items at the Lowest Prices',
        29 => 'Shop Every Day to Get The Best Deals.',
        30 => 'Good Things Come to Those Who Shop Around.',
        31 => 'Buy It Now, Get It Fast.',
        32 => 'New Arrivals All the Time.',
        33 => 'We Make Shopping Easy, So You Can Shop More.',
        34 => 'Look Sharp, Spend Less',
        35 => 'Every Day Is a Good Day to Shop.',
        36 => 'The Best Deals Are Waiting for You!',
        37 => 'Amazing Shopping Experience from The Comfort of Your Home.',
        38 => 'You Deserve the Best Selection and Lowest Prices Around!',
        39 => 'Satisfy Your Needs at An Affordable Price.',
        40 => 'Amazing Prices. Great choices.',
        41 => 'Here to make your shopping easier.',
        42 => 'Must have it? We\'ve got it.',
        43 => 'Where Quality Meets Savings.',
        44 => 'Your place for shopping and leisure.',
        45 => 'Where the world comes to shop',
        46 => 'It\'s never too late to buy something nice for yourself.',
        47 => 'Shop our store and satisfy your needs.',
        48 => 'Our prices are unbeatable!',
        49 => 'The best prices open to you.',
        50 => 'You never know what you might find at our store!',
        51 => 'Shop smarter, not harder. We\'re here for you.',
        52 => 'Find what you need, fast.',
        53 => 'Shop from the comfort of your home.',
        54 => 'Save time and money with us.',
        55 => 'Get the best deals online.',
        56 => 'Shop the latest trends, all in one place.',
        57 => 'Experience the convenience of online shopping.',
        58 => 'We\'ve got what you want, when you want it.',
        59 => 'Find the perfect gift for any occasion.',
        60 => 'Get the best deals on top brands.',
        61 => 'Shop online and save time and money.',
        62 => 'Experience the convenience of 24/7 shopping.',
        63 => 'Discover new products and amazing deals every day.',
        64 => 'Buy with confidence – we guarantee 100% satisfaction.',
        65 => 'Get the best prices on the latest products.',
        66 => 'Shop with us and get amazing discounts and promotions.',
        67 => 'Discover the best deals online with us.',
        68 => 'Get the best value for your money with us.',
        69 => 'Find everything you need in one place.',
        70 => 'Shop the world from your doorstep.'
    );

    /**
     * @var array
     */
    public static $tagline = array(
        1 => 'A few clicks is all it takes.',
        2 => 'All the best for a whole lot less',
        3 => 'An exciting place for you to shop.',
        4 => 'We are anything but ordinary',
        5 => 'Discover your favorite place to shop',
        6 => 'Every product delivered to you',
        7 => 'Shop better, feel better',
        8 => 'For the person who has everything, we have everything else.',
        9 => 'If we don\'t sell it, you won\'t need it.',
        10 => 'Lowest prices guaranteed!',
        11 => 'The best is what we\'re all about.',
        12 => 'The one stop all around shop.',
        13 => 'Where else? Than here.',
        14 => 'You need it, we\'ve got it.',
        15 => 'You want lower prices, we hear you.',
        16 => 'Shop with us and see how great we are!',
        17 => 'Be free to get what you need online!',
        18 => 'Quality Matters Here!',
        19 => 'Everything you need, and nothing you don\'t.',
        20 => 'We Sell For Less!',
        21 => 'The Best of Everything, Naturally',
        22 => 'You\'ll Like Our Selection',
        23 => 'We maximize customer value!',
        24 => 'Quality. Choice. Value.',
        25 => 'Everyday Deals For Everyday People',
        26 => 'The Store With More For Less',
        27 => 'We have everything you want at the lowest prices possible',
        28 => 'Get more for your money',
        29 => 'The ultimate shopping experience',
        30 => 'Shopping gets the mood rolling',
        31 => 'Shop today, enjoy tomorrow.',
        32 => 'Our store will inspire you to buy more.',
        33 => 'We have what you seek',
        34 => 'You need it, you want it, we got it.',
        35 => 'Shop smart, shop online',
        36 => 'We\'ve got what you\'re looking for!',
        37 => 'Finding the perfect item has never been easier',
        38 => 'The quality product you expect.',
        39 => 'We make online selling superbly easy',
        40 => 'Special products for our special customers.',
        41 => 'Combining quality and reliability in one place!',
        42 => 'We deliver more than your expectations',
        43 => 'We got it all for you!',
        44 => 'One stop solution for all your needs',
        45 => 'The most reliable site for your shopping needs',
        46 => 'You\'ll never know what you\'ve been missing until you shop with us.',
        47 => 'Shopping is fun again!',
        48 => 'A place where you can find anything and everything for your home',
        49 => 'Find it here, buy it now',
        50 => 'You\'ll always have a great selection with all the latest trends just a click away!',
        51 => 'A dynamic shopping experience.',
        52 => 'All you need is here!',
        53 => 'You\'re bound to find more.',
        54 => 'We make shopping easy.',
        55 => 'The Internet’s largest online store.',
        56 => 'The best value in the neighborhood.',
        57 => 'The best is what we’re all about.',
        58 => 'Right store. Right price.',
        59 => 'We go above and beyond what you expect.',
        60 => 'We provide everything you need at the most affordable pricing.',
        61 => 'Shop with us and get the best deals online.',
        62 => 'Discover the latest trends, all under one roof.',
        63 => 'Shop with us and shop with peace of mind.',
        64 => 'Find what you love, at a price you\'ll love.',
        65 => 'The best deals are just a click away.',
        66 => 'The best prices, the best selection.',
        67 => 'Get the greatest online prices when you shop with us.',
        68 => 'Find the perfect gift, every time.',
        69 => 'Experience the convenience of online shopping with us.',
        70 => 'Hassle-free shopping, every time.'
    );


    /**
     * @var array
     */
    public static $aboutUsTitle = array(
        1 => 'About Us',
        2 => 'Shop With Us',
        3 => 'Why Choose Us',
        4 => 'About',
        5 => 'Who We Are',
        6 => 'Our Company',
        7 => 'Our Mission',
        8 => 'Why Buy From Us',
        9 => 'Why Us?',
        10 => 'What Sets Us Apart',
        11 => 'Get To Know Us',
        12 => 'Read About Us',
        13 => 'Our Story',
        14 => 'Who Are We?',
        15 => 'Welcome To Our Store',
        16 => 'Meet Our Brand',
        17 => 'Learn About Us',
        18 => 'Explore Our Store',
        19 => 'Why We Rock!',
        20 => 'Reasons To Count On Us',
        21 => 'Our Philosophy',
        22 => 'Our Goals',
        23 => 'Company Overview',
        24 => 'Who We Are',
        25 => 'A Brief Introduction About Us',
        26 => 'Discover Us',
        27 => 'Our Story',
        28 => 'Welcome to Our Store',
        29 => 'Our Commitment to Excellence',
        30 => 'Our Mission and Values',
        31 => 'Our Journey',
        32 => 'We Are Commited & Dedicated',
        33 => 'More About Us',
        34 => 'The Company',
        35 => 'Learn More About Us',
        36 => 'Our Products and Services',
        37 => 'Our Core Values and Practices',
        38 => 'Meet the Team',
        39 => 'Our Company\'s History and Mission',
        40 => 'Our Core Values and Practices'
    );


    /**
     * @var array
     */
    public static $aboutUs = array(
        1 => 'Do you want bang for the buck products? Then you came to the right store as that is our company\'s main focus. To bring out quality items for the most affordable prices.',
        2 => 'Our company is focused on providing whatever it is that is in trend or what is needed. Our motto is Whatever you have as a main priority, we have it here',
        3 => 'We update our products everyday and main its quality to ensure that we provide the best for our best customers.',
        4 => 'We give you a whole new shopping experience to make shopping fun and affordable.',
        5 => 'We\'re providers of great! We provide and maintain great quality products for the satisfaction of our customers.',
        6 => 'Our purpose to provide great service and great products.',
        7 => 'Our products are always changing to adapt to the latest trends to satisfy our current and future customers!',
        8 => 'The search is over! Welcome to our one stop shop wherein you can find everything that you want and everything that you\'ll ever want.',
        9 => 'The goal of our company is to ease the process of shopping, which is why we deliver everything right at your doorstep! Click now and we deliver tomorrow!',
        10 => 'Our shop has no limit! We are here to provide you a variety of premium choices at affordable prices.',
        11 => 'Welcome to our store! We are here to give you our amazing service with our amazing products! Check out our inventory now!',
        12 => 'We know you want the best, which is why we have gathered the best and unique products in our store to provide you with everything that you need and want.',
        13 => 'Our online store is always here to serve you only the best! What are you waiting for? ',
        14 => 'Premium, High Quality and Affordable Products! That is what we are all about and we plan to keep it that way while maintaining high level of service.',
        15 => 'This is more than just a store! Our shop is a place of needs and wants. Anything you want or need, we have it. We are always updated and always changing.',
        16 => 'We have evolved from a simple store into great and all in one provider of trending items! We will always maintain our premium items and great service.',
        17 => 'Are you on the look out for unique and amazing products? Something that is not in every other store out there? Then welcome to our unique one stop shop that will make you want to buy things that you need and don\'t need!',
        18 => 'Welcome shopper! Explore our variety of products and enjoy the cheap prices that we have here. These affordable prices are especially made for our special customers to make their days even more special!',
        19 => 'Our store revolves around 2 things, that is affordability and quality of the products that we have and will have here in our site. With this in mind, rest assured that everything that we will serve is in its best and high quality condition followed by a cheap price.',
        20 => 'Who says that you need to spend a lot in order to get high end products? Well that\'s not how we do it in our store. In here, we believe that great and premium things can be purchased at the most affordable prices. So what are you waiting for? Go and browse in our store and take a look at our amazing products!',
        21 => 'We put a lot of effort and work, in order to provide the most amazing premium and affordable products at there in the market, and put it here in our store!',
        22 => 'Why are you holding out? Visit us to experience our superb service and learn more about what we have to offer. Browse our extensive selection of high quality goods offered at unbelievable discounts. Spend money now and save a lot.',
        23 => 'Welcome to the place where you can find all of your favorite products. We are committed to giving you the best products possible, placing a strong emphasis on both value and quality.',
        24 => 'You are in the proper place if you seek the best and most spectacular stuff. We provide the most fantastic, high quality goods available.',
        25 => 'You won\'t find a better selection of products of higher quality anywhere else than what we have to offer. Start your purchases here!',
        26 => 'We provide you with the broadest range of top notch goods. Don\'t believe anything we say. Place your purchase right now!',
        27 => 'We can help if you\'re looking for the highest quality and most distinctive products. We offer a huge range of excellent products.',
        28 => 'It has never been so simple to find high quality products. We are the ideal supplier of premium quality products at competitive prices.',
        29 => 'Are you willing to accept our remarkable offers? We are here to offer the highest quality goods at the most affordable pricing imaginable!',
        30 => 'We swore to uphold high standards of quality and to always adhere to those standards in everything we do, both to ourselves and to our clients.',
        31 => 'Offering a great variety of outstanding products with excellent quality standards and competitive pricing. Stop holding off and start saving with us.',
        32 => 'Find the greatest items at your preferred one stop shop, and prepare to be astounded by the incredible deals.',
        33 => 'We are delighted by and grateful for your visit to our website. We strive to give you the finest service possible while also giving you high quality items since we love our clients and want to keep them.',
        34 => 'In order to improve their experience and encourage them to return because we care, we are working hard to deliver the least expensive and most dependable items to our cherished clients.',
        35 => 'We established this store to provide you with a vast selection of goods you didn\'t know you needed! Our shop offers a unique experience that is unmatched.',
        36 => 'We all desire the finest, which is what we all want. We are prepared to provide you everything at its finest since we just want the best for you.',
        37 => 'Our business is here to give you everything you want and need at the lowest prices on the market.',
        38 => 'Every business has its unique success formula. The quality of the services and goods that we offer and supply is our secret.',
        39 => 'We all desire the finest, which is what we all want. We are prepared to provide you everything at its finest since we just want the best for you.',
        40 => 'Because our firm only employs excellent individuals, we only offer premium items to our most loyal clients. You are that!',
        41 => 'Our business pays attention to what is required, what is vital, and what is popular today, which is why we have high quality and well liked items in our shop.',
        42 => 'Do you desire the top things at the lowest prices? Given that we have both of what you\'re seeking for, you\'ve come to the perfect place. One of our primary offerings is Top Quality and Low Price',
        43 => 'We are here to provide you with fantastic goods at reasonable costs, hence the phrase Bang for Your Buck.',
        44 => 'Enjoy looking at the goods we have featured on our website. Our staff carefully selects these depending on what\'s new and how well made it is. We are present and available to help.',
        45 => 'To assist our consumers obtain what they want at a fair price, our primary objective is to offer superior products that are as inexpensive as possible.',
        46 => 'Our purpose is straightforward: to assist you in saving money at the checkout. We have compiled a list of some of the most reasonably priced high quality items on the market.',
        47 => 'We are all about three things: premium, low cost, and high quality products that will undoubtedly meet your needs.',
        48 => 'We are here to assist you. We offer excellent service. We offer great quality products for low prices. Everything is available in our shop!',
        49 => 'Our organization is here to give you with whatever you want and desire, all at the most competitive pricing on the market.',
        50 => 'You will undoubtedly return to our store for more, since we offer a lot of things that will pique your interest.',
        51 => 'Welcome to our company! We are a team of dedicated professionals who are passionate about what we do. Our mission is to provide top-quality products and services to our customers, and we strive to exceed their expectations every day.',
        52 => 'Our company was founded on the principles of integrity, innovation, and customer satisfaction. We take pride in our work and are committed to providing the best experience possible for our clients. We are here to provide whatever it is that you may need.',
        53 => 'We are a "customer-comes-first" type of business, with a long history of serving our community. Our team is made up of skilled professionals who are dedicated to delivering the best products and services to our customers.',
        54 => 'Our store was founded on the principles of convenience and affordability. We are committed to making shopping easy and accessible for our customers, and we offer a variety of payment options and Fast shipping to ensure a hassle-free experience.',
        55 => 'We take pride in our commitment to sustainability and ethical practices. We are dedicated to using environmentally friendly materials and processes in all of our operations. We also provide great customer service followed by convenience in shopping through nationwide delivery.',
        56 => 'Our success is built on the relationships we have with our customers and partners. We value open communication and are always looking for ways to exceed their expectations. We also give importance to the quality and affordable of the products in our inventory.',
        57 => 'We are always looking for new opportunities to grow and expand our business. Whether it\'s through partnerships, new product lines, or entering new markets, we are constantly seeking out ways to drive success and deliver value to our customers.In addition to our core products and services, we also offer a range of support and training options to help our customers get the most out of their experience with us.',
        58 => 'Our company focuses on providing affordable and top notch quality products. We also believe in the power of diversity and inclusion and strive to create a workplace that is welcoming and supportive of all individuals.',
        59 => 'Our one-stop-shop provides our customers with only the best when it comes to the quality of the products and its affordability. Our website is also user-friendly and easy to navigate, with advanced search and filtering options to help customers find exactly what they\'re looking for.',
        60 => 'Affordability and Quality are our top 2 concerns when it comes to our business. We want our customers to be able to purchase high end products at a very affordable costs. Also, Our team is dedicated to delivering the highest level of customer service and satisfaction. We offer fast and reliable shipping, easy returns, and responsive customer support to ensure that our customers have a seamless shopping experience.',
        61 => 'Our store is dedicated to providing the best shopping experience possible. From the quality of our products to the convenience of our website, we strive to go above and beyond for our customers.',
        62 => 'At our store, we believe in the power of convenience. We offer Fast shipping and a variety of payment options to make shopping easy and hassle-free for our customers. We will deliver high end products in their 100% condition.',
        63 => 'Our store is built on a foundation of quality and affordability. We offer a wide range of products at competitive prices, and we are always looking for ways to improve and grow. We will never stop providing top notch products followed by amazing customer service.',
        64 => 'We are a store that focuses on customer satisfaction and high product quality. Our team is dedicated to providing top-notch service and ensuring that our customers have a positive shopping experience. We provide the best items to our best customers.',
        65 => 'We are constantly expanding our product offerings and are always on the lookout for new and innovative products to add to our store. We strive to provide our customers with the best selection and value for their money.',
        66 => 'We are an online store with a commitment to maintaining product quality and customer satisfaction. In addition to offering eco-friendly and affordable products, we also support various charitable initiatives. We are committed to delivering the best shopping experience possible and look forward to serving you.',
        67 => 'We are dedicated to providing top-notch customer service. Whether you have a question about a product or need help with an order, our team is always here to assist you. Other than customer service, we provide 100% affordable products at reasonable prices.',
        68 => 'Our store revolves around the power of choice. We offer a wide range of products in various categories, so you can find exactly what you\'re looking for at the best price. Not only that, we also provide great customer service for our customers who are in need of assistance.',
        69 => 'We are a customer-focused online store, committed to delivering a seamless shopping experience for our clients. Our team is made up of skilled professionals who are dedicated to providing top-notch service. We take care of our items and deliver them in perfect conditions.',
        70 => 'We are dedicated to providing top-quality products at affordable prices. We have a wide selection of items in various categories, and we are constantly adding new products to our inventory. We also provide a 24/7 support system to ensure the satisfaction of our customers.'
    );


    /**
     * @var array
     */
    public static $shopTitle = array(
        1 => 'Shop',
        2 => 'Our Selection',
        3 => 'Browse Products',
        4 => 'Our Products',
        5 => 'What We Offer',
        6 => 'Products',
        7 => 'Our Store',
        8 => 'Online Store',
        9 => 'We Recommend',
        10 => 'The Shop',
        11 => 'Marketplace',
        12 => 'Featured Products',
        13 => 'Offer',
        14 => 'Our Collection',
        15 => 'Latest Products',
        16 => 'Shop Online',
        17 => 'The Goods',
        18 => 'Special Offers',
        19 => 'Great Selection',
        20 => 'Choose Your Products',
        21 => 'Discover Our Selection',
        22 => 'Shop Our Store',
        23 => 'Amazing Perfect Products',
        24 => 'Shop Our Collection',
        25 => 'See Our Collection',
        26 => 'Discover Our Products',
        27 => 'Find What You\'re Looking For',
        28 => 'Our Catalog',
        29 => 'Explore Unique Items',
        30 => 'View Our Products',
        31 => 'Shop Our Wide Selection',
        32 => 'Find What You Need in Our Store',
        33 => 'Discover Our Products',
        34 => 'We\'ve Got What You\'re Looking For',
        35 => 'Shop With Confidence',
        36 => 'Check Us Out',
        37 => 'Choose Our Items',
        38 => 'The Perfect Items',
        39 => 'Take a Tour',
        40 => 'What you seek'
    );


    /**
     * @var array
     */
    public static $buttonName = array(
        1 => 'Buy Now',
        2 => 'Place Order',
        3 => 'Start Shopping',
        4 => 'Make Purchase',
        5 => 'Shop',
        6 => 'Get Started',
        7 => 'Add to Cart',
        8 => 'View Products',
        9 => 'Shop Now',
        10 => 'Purchase',
        11 => 'Select Product',
        12 => 'Click To Shop',
        13 => 'Buy It Now',
        14 => 'Get Product  ',
        15 => 'Learn More',
        16 => 'Show More',
        17 => 'See Details',
        18 => 'Start Order',
        19 => 'Discover',
        20 => 'Explore',
        21 => 'Buy & Save',
        22 => 'Shop It',
        23 => 'Claim',
        24 => 'Choose',
        25 => 'Buy & Enjoy',
        26 => 'Get',
        27 => 'View',
        28 => 'Grab Item',
        29 => 'Grab',
        30 => 'Secure Item',
        31 => 'Order Now',
        32 => 'Add to Order',
        33 => 'View More',
        34 => 'Purchase Item',
        35 => 'Secure',
        36 => 'Get It Now',
        37 => 'Check Now',
        38 => 'Shop Now',
        39 => 'Browse',
        40 => 'View'
    );



    /**
     * @var array
     */
    public static $popularTitle = array(
        1 => 'Featured Products',
        2 => 'Popular Products',
        3 => 'Hottest Sellers',
        4 => 'Recommended Products',
        5 => 'What\'s Trendy',
        6 => 'What\'s New',
        7 => 'Best Deals',
        8 => 'Must Have',
        9 => 'Selected For You',
        10 => 'Premium Selection',
        11 => 'What We Think You Will Like',
        12 => 'We Recommend',
        13 => 'Our Favorites',
        14 => 'Hot Products',
        15 => 'New Arrivals',
        16 => 'Featured Items',
        17 => 'Hottest Items',
        18 => 'Hot Deals',
        19 => 'Amazing Offers',
        20 => 'Top Sellers',
        21 => 'Best Sellers',
        22 => 'Most Popular Products',
        23 => 'Best-Selling Products',
        24 => 'Highly-Rated Products',
        25 => 'Popular Picks',
        26 => 'Top Trends',
        27 => 'Customer-Favorite Products',
        28 => 'Top-Selling Items',
        29 => 'Most Popular Items',
        30 => 'Best-Reviewed Products',
        31 => 'Trending Picks',
        32 => 'Must-Have Items',
        33 => 'Best-Loved',
        34 => 'Top New Items',
        35 => 'What\'s In',
        36 => 'In-Demand Items',
        37 => 'Spotlight Products',
        38 => 'New Items',
        39 => 'Latest Releases',
        40 => 'Just In'
    );

    /**
     * @var array
     */
    public static $contactTitle = array(
        1 => 'How Can We Help?',
        2 => 'We\'re here for you!',
        3 => 'Don\'t Hesitate to Connect With Us',
        4 => 'Hi, there!',
        5 => 'Contact The Help Team',
        6 => 'Customer support team, standing by.',
        7 => 'Let\'s Talk, But You First.',
        8 => 'Hello there! Give us a ring',
        9 => 'We\'d love to hear from you',
        10 => 'Still need help?',
        11 => 'Oh hey there!',
        12 => 'Got a question for us?',
        13 => 'Contact Support',
        14 => 'Contact Customer Service',
        15 => 'Looking for help with..?',
        16 => 'Write Us A Message',
        17 => 'Need To Contact Us?',
        18 => 'Let\'s start a conversation',
        19 => 'Give us a shout',
        20 => 'Get the info you\'re looking for',
        21 => 'Reach Out to Us',
        22 => 'Ask Us a Question about Our Services',
        23 => 'Get in Touch with Our Customer Service',
        24 => 'Ask Us a Question via Email',
        25 => 'Send Us a Message via Phone',
        26 => 'Contact Our Management Team',
        27 => 'Connect with Us on Social Media',
        28 => 'Get in Touch with Our Support Team',
        29 => 'Give Us a Call',
        30 => 'Send Us an Email',
        31 => 'Connect with Our Team',
        32 => 'Contact Our Team',
        33 => 'Get in Contact',
        34 => 'Ask Us a Question',
        35 => 'Send Us a Message',
        36 => 'Say Hello',
        37 => 'Reach Out',
        38 => 'Connect with Us',
        39 => 'Get in Touch',
        40 => 'Contact Us'
    );

    /**
     * @var array
     */
    public static $contactContent = array(
        1 => 'For all enquiries, please don\'t hesitate to contact us.',
        2 => 'Need something? We\'re here to help!',
        3 => 'Don\'t be shy, ask away!',
        4 => 'We have a friendly customer support team that\'s always just a click away.',
        5 => 'If you have any questions or queries, a member of our staff will always be happy to help.',
        6 => 'Feel free to contact us by telephone or email and we will be sure to get back to you as soon as possible.',
        7 => 'We love to hear from our amazing customers!',
        8 => 'Always humans, never bots. The hands-down, sharpest and friendliest support team in the business.',
        9 => 'Looking for a quick answer to your question? We\'re here for you',
        10 => 'Need a hand? Here\'s how to reach us.',
        11 => 'Request a call, chat online and more.',
        12 => 'Talk to a member of our customer support team.',
        13 => 'Question not answered yet? We\'re here to help',
        14 => 'Let\'s talk about your concern.',
        15 => 'Send us a message and we will be in touch with you.',
        16 => 'Still need help? How would you like us to get in touch?',
        17 => 'Tell us about your issue so we can help you more quickly',
        18 => 'We\'ve got all kinds of ways to help you out. Here\'s how you can contact us.',
        19 => 'If you\'re looking at this page, you\'re in what we call "you do need help" stage and we got you!',
        20 => 'Our door is always open to help you out, or you can just share your excitement with us.',
        21 => 'Whether you\'re curious about our service, products etc - we\'re ready to answer any and all questions',
        22 => 'Want to get in touch? We\'d love to hear from you. Here\'s how you can reach us...',
        23 => 'We\'re here to help and answer any question you might have. We look forward to hearing from you',
        24 => 'Drop us a line, give us a heads up if you\'re interested in sharing what you have in mind.',
        25 => 'Are you a customer who needs help? Our amazing customer support team is here for you!',
        26 => 'Let\'s get this conversation started. Tell us what you have in mind and we\'ll get in touch as soon as we can.',
        27 => 'We appreciate you here in our business. How can we help you today?',
        28 => 'If you have any questions, please feel free to let us know.',
        29 => 'We\'re always here, ready and waiting to answer your questions.',
        30 => 'Thanks for reaching out. What questions do you need help with?',
        31 => 'Here in our store, we are dedicated in making you have an amazing online shopping experience.',
        32 => 'Didn\'t find what you\'re looking for? We\'d love to hear from you.',
        33 => 'Questions? Concerns? Drop us your details to receive a call back from us.',
        34 => 'Got questions? Want to tell us something? Looking for a service or a product?',
        35 => 'Need to get in touch with the team? We\'re all ears.',
        36 => 'Our team is happy to answer all your questions.',
        37 => 'What can we help you with?',
        38 => 'We see that you have some questions, let us help you with that.',
        39 => 'Please let us know your concern, and we\'ll be in touch with you shortly',
        40 => 'Want to find the answer to your particular problem or concern? Let\'s talk',
        41 => 'We\'re here for you and we\'re wearing our "always ready to help" hats.',
        42 => 'Let\'s have a chat and talk about your question.',
        43 => 'Need to get in contact or just want to send a message?',
        44 => 'Thanks for visiting! We hope that you have found what you needed in our website. If not, please feel free to contact us.',
        45 => 'Got a question that you can\'t seem to figure out? We\'d love to hear from you!',
        46 => 'If you have questions or feedback about an order, here\'s how to get in touch.',
        47 => 'We provide the exceptional service we\'d want to experince ourselves.',
        48 => 'You can contact us online, visit or give us a call.',
        49 => 'We will help you get in touch with the right people!',
        50 => 'You are always welcome to contact us with questions and inquiries.',
        51 => 'Thank you for visiting our website. If you have any questions or comments, please don\'t hesitate to contact us. We\'d love to hear from you!',
        52 => 'We value your feedback and are always happy to help with any questions or concerns you may have. Please don\'t hesitate to contact us at any time.',
        53 => 'For inquiries, comments, or support, please don\'t hesitate to get in touch with us. We\'re always happy to help and look forward to hearing from you.',
        54 => 'Need help with your order, have a question about our products, or just want to say hello? Contact us anytime and we\'ll be happy to assist you.',
        55 => 'We\'re here to help with any questions or issues you may have. Please don\'t hesitate to reach out to us through our contact form, email, or phone.',
        56 => 'Thank you for considering our products and services. If you have any questions or need assistance, please don\'t hesitate to contact us.',
        57 => 'We\'re always happy to answer any questions or concerns you may have. Please don\'t hesitate to get in touch with us through our contact form or by phone.',
        58 => 'For any inquiries or support, please don\'t hesitate to contact us. We\'ll do our best to respond to your message as soon as possible.',
        59 => 'If you have any questions or comments, we\'d love to hear from you. Please don\'t hesitate to get in touch with us through our contact form, email, or phone.',
        60 => 'We\'re here to help with any issues or questions you may have. Please don\'t hesitate to contact us and we\'ll do our best to assist you.',
        61 => 'Thank you for visiting our website. If you have any questions or need assistance, please don\'t hesitate to reach out to us.',
        62 => 'We value your feedback and are always happy to help with any questions or concerns you may have.',
        63 => 'For inquiries, comments, or support, please don\'t hesitate to contact us. We\'re here to help and look forward to hearing from you.',
        64 => 'Thank you for reaching out to us! If you have any questions, comments, or concerns, please don\'t hesitate to contact us. We\'ll do our best to get back to you as soon as possible.',
        65 => 'We value your feedback and are here to help with any questions or issues you may have. Please don\'t hesitate to get in touch with us through the contact form provided.',
        66 => 'If you have any questions or concerns, we\'d love to hear from you. Please use the contact form on our website or send us an email, and we\'ll get back to you as soon as we can.',
        67 => 'We\'re always happy to hear from our customers! If you have any questions, comments, or suggestions, please don\'t hesitate to reach out to us. We\'ll do our best to respond to your inquiry as quickly as possible',
        68 => 'Your feedback is important to us. If you have any questions, comments, or suggestions, please don\'t hesitate to reach out to us through the contact form on our website or by email. We\'ll do our best to get back to you as soon as we can.',
        69 => 'Thank you for taking the time to contact us. If you have any questions, concerns, or comments, please don\'t hesitate to reach out. We\'ll do our best to get back to you as soon as we can.',
        70 => 'We\'re here to help! If you have any questions or need assistance with anything, please don\'t hesitate to contact us. We\'ll do our best to get back to you as soon as possible.'
    );
}
